"""empty message

Revision ID: 1ef28216da55
Revises: 23fdf424494d
Create Date: 2025-11-18 08:33:18.564639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef28216da55'
down_revision: Union[str, Sequence[str], None] = '23fdf424494d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO type (name) VALUES ('temperature');")
    op.execute("INSERT INTO type (name) VALUES ('pressure');")
    op.execute("INSERT INTO type (name) VALUES ('humidity');")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
