"""empty message

Revision ID: 23fdf424494d
Revises: 
Create Date: 2025-11-14 16:48:07.364431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fdf424494d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id_type', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_type'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sensor',
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_type'], ['type.id_type'], ),
    sa.PrimaryKeyConstraint('mac')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mac'], ['sensor.mac'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('sensor')
    op.drop_table('type')
    # ### end Alembic commands ###
